[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "slovorez"
version = "0.1.0"
dependencies = [
    "keras",
    "pandas"
]

[project.optional-dependencies]
tf = ["tensorflow-cpu"]
tf-gpu = ["tensorflow[and-cuda]"]
torch = ["torch"]

dev = [
    "tensorflow-cpu",
    "torch",
    "pymorphy3"
]

[tool.setuptools.packages.find]
where = ["src"]
